# Generated by Django 3.2.18 on 2023-05-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idealmovie',
            field=models.ManyToManyField(blank=True, null=True, related_name='choiceidealuser', to='movies.Movie'),
        ),
    ]
