# Generated by Django 3.2.18 on 2023-05-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(default='새싹', max_length=20),
        ),
    ]
